# Generated by Django 5.1 on 2024-08-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_maker', models.CharField(max_length=255)),
                ('news_text', models.TextField()),
                ('reliability_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
