# Generated by Django 5.1 on 2024-08-30 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='reliability',
            new_name='reliability_score',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
